### PR TITLE
Add coverage reporting

### PR DESCRIPTION
**Pull request by brennv**

### CODE REVIEW

**Comment by brennv** [comment]
The issue reported by codecov-io above should be resolved by the repository owner or an org member authorizing coverage reporting here: https://codecov.io/gh/diamond-org/flask-diamond

**Comment by iandennismiller** [comment]
Hey @brennv - I apologize for the major delay on reviewing this.  I'd like to merge the changes for code coverage, but this pull request appears to include a lot of superfluous git history (i.e. 64 commits).  Can you prune this down to a single commit with the just the 3 file changes?  It might be easier to create a fresh pull request instead of trying to back out this one.

**Comment by brennv** [comment]
@iandennismiller Would you like contributor PRs to go to master branch or the develop branch?

**Comment by iandennismiller** [comment]
That's a great question. I would like PRs to the develop branch. Sorry for the ambiguity about this because I see how that directly lead to the extra commits in the PR.

You made me realize the develop branch was lagging behind master.  So, I've updated develop to the latest.  If you pull from develop, then submit a PR against that, it will be perfect.  Again, I'm sorry for the extra work.

**Pull request closed without merging**
